version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  postgre_migrations:
    build: migrations/.
    environment:
      DB_HOST: "db"
    depends_on:
      db:
        condition: service_healthy

  web:
    build: news_backend/.
    command: python app.py
    ports:
      - "6543:6543"
    depends_on:
      - postgre_migrations

  frontend:
    build: frontend/.
    ports:
      - "3000:3000"
